CREATE TABLE Hospital (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR,
	Address VARCHAR
);

CREATE TABLE Doctor (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR,
	HospitalID INTEGER,
	Specialization VARCHAR,
	Contact_No VARCHAR,
	FOREIGN KEY(HospitalID) REFERENCES Hospital(ID)
);

CREATE TABLE Patient (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR,
	Address VARCHAR,
	Contact_No VARCHAR
);

CREATE TABLE Condition (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR,
	Category VARCHAR
);

CREATE TABLE Appointment (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	DoctorID INTEGER,
	PatientID INTEGER,
	ConditionID INTEGER,
	Timestamp DATETIME,
	Fees DECIMAL,
	FOREIGN KEY(DoctorID) REFERENCES Doctor(ID),
	FOREIGN KEY(PatientID) REFERENCES Patient(ID),
	FOREIGN KEY(ConditionID) REFERENCES Condition(ID)
);

CREATE TABLE Pharmacy (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	Name VARCHAR,
	Address VARCHAR
);

CREATE TABLE Invoice (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	PharmacyID INTEGER,
	AppointmentID INTEGER,
	Amount DECIMAL,
	FOREIGN KEY(PharmacyID) REFERENCES Pharmacy(ID),
	FOREIGN KEY(AppointmentID) REFERENCES Appointment(ID)
);

